version: '3.7'

services:
    web:
        env_file:
            - .env
        build: .
        command:
            - /bin/bash
            - -c
            - python3 /code/twitter_bot.py && python3 /code/alts/xame/twitter_bot.py && python3 /code/alts/uva/twitter_bot.py && python3 /code/alts/mevu/twitter_bot.py && python3 /code/alts/zark/twitter_bot.py

        volumes:
            - .:/code


