version: '3.7'

services:
    web:
        env_file:
            - .env
        build: .
        command: bash -c "python3 /code/fortune_bot.py && python3 /code/twitter_unfollow.py"
        volumes:
            - .:/code


