name: Bluesgivando

on: push
#  schedule:
#    - cron: '0 * * * *'

jobs:
  tweet:
    name: Skeet
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Keep this repo alive
        uses: gautamkrishnar/keepalive-workflow@master

      - name: Set up Python 🐍
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Cache Python packages 💾
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install packages ⚙
        run: |
          python -m pip install --upgrade pip
          pip install bs4 atproto requests fortune

      # Use HEREDOC for `run` to escape possible single and double quotes in the message.
      - name: Run all contest scripts 🐦
        env:
          BSKY_HANDLE:  ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD:  ${{ secrets.BSKY_PASSWORD }}
          BSKY_HANDLE_LUFF:  ${{ secrets.BSKY_HANDLE_LUFF }}
          BSKY_PASSWORD_LUFF:  ${{ secrets.BSKY_PASSWORD_LUFF }}
          BSKY_HANDLE_RIL:  ${{ secrets.BSKY_HANDLE_RIL }}
          BSKY_PASSWORD_RIL:  ${{ secrets.BSKY_PASSWORD_RIL }}
          BSKY_HANDLE_JAM:  ${{ secrets.BSKY_HANDLE_JAM }}
          BSKY_PASSWORD_JAM:  ${{ secrets.BSKY_PASSWORD_JAM }}
          BSKY_HANDLE_XAM:  ${{ secrets.BSKY_HANDLE_XAM }}
          BSKY_PASSWORD_XAM:  ${{ secrets.BSKY_PASSWORD_XAM }}
          BSKY_HANDLE_ZARK:  ${{ secrets.BSKY_HANDLE_ZARK }}
          BSKY_PASSWORD_ZARK:  ${{ secrets.BSKY_PASSWORD_ZARK }}
          BSKY_HANDLE_UVA:  ${{ secrets.BSKY_HANDLE_UVA }}
          BSKY_PASSWORD_UVA:  ${{ secrets.BSKY_PASSWORD_UVA }}
          BSKY_HANDLE_LUFI:  ${{ secrets.BSKY_HANDLE_LUFI }}
          BSKY_PASSWORD_LUFI:  ${{ secrets.BSKY_PASSWORD_LUFI }}
          BSKY_HANDLE_WOBA:  ${{ secrets.BSKY_HANDLE_WOBA }}
          BSKY_PASSWORD_WOBA:  ${{ secrets.BSKY_PASSWORD_WOBA }}
          BSKY_HANDLE_MAJ:  ${{ secrets.BSKY_HANDLE_MAJ }}
          BSKY_PASSWORD_MAJ:  ${{ secrets.BSKY_PASSWORD_MAJ }}
          BSKY_HANDLE_ZELD:  ${{ secrets.BSKY_HANDLE_ZELD }}
          BSKY_PASSWORD_ZELD:  ${{ secrets.BSKY_PASSWORD_ZELD }}
          BSKY_HANDLE_IFU:  ${{ secrets.BSKY_HANDLE_IFU }}
          BSKY_PASSWORD_IFU:  ${{ secrets.BSKY_PASSWORD_IFU }}
        run: python bluesgive.py

      - name: Atualizar arquivos de interações
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git status  # Verificar se há mudanças detectadas
          git add -f alts/*.json  # Forçar adição dos arquivos de interações
          git commit -m "Atualizar arquivos de interações [skip ci]" || echo "Nenhuma alteração para fazer commit."
          git push || echo "Nenhuma alteração para fazer push."
