name: factando


on:

    schedule:

        - cron: '0 15 * * 1-5'

jobs:

    build:

        runs-on: ubuntu-latest


        steps:

            - uses: actions/checkout@v2


            - name: Make envfile

              uses: SpicyPizza/create-envfile@v1

              with:


                  envkey_CONSUMER_KEY_XAME: ${{ secrets.CONSUMER_KEY_XAME }}

                  envkey_CONSUMER_SECRET_XAME: ${{ secrets.CONSUMER_SECRET_XAME }}

                  envkey_ACCESS_TOKEN_XAME: ${{ secrets.ACCESS_TOKEN_XAME }}

                  envkey_ACCESS_TOKEN_SECRET_XAME: ${{ secrets.ACCESS_TOKEN_SECRET_XAME }}

                  envkey_CONSUMER_KEY_ZARK: ${{ secrets.CONSUMER_KEY_ZARK }}

                  envkey_CONSUMER_SECRET_ZARK: ${{ secrets.CONSUMER_SECRET_ZARK }}

                  envkey_ACCESS_TOKEN_ZARK: ${{ secrets.ACCESS_TOKEN_ZARK }}

                  envkey_ACCESS_TOKEN_SECRET_ZARK: ${{ secrets.ACCESS_TOKEN_SECRET_ZARK }}

                  envkey_CONSUMER_KEY_RIL: ${{ secrets.CONSUMER_KEY_RIL }}

                  envkey_CONSUMER_SECRET_RIL: ${{ secrets.CONSUMER_SECRET_RIL }}

                  envkey_ACCESS_TOKEN_RIL: ${{ secrets.ACCESS_TOKEN_RIL }}

                  envkey_ACCESS_TOKEN_SECRET_RIL: ${{ secrets.ACCESS_TOKEN_SECRET_RIL }}

                  envkey_CONSUMER_KEY_MEVU: ${{ secrets.CONSUMER_KEY_MEVU }}

                  envkey_CONSUMER_SECRET_MEVU: ${{ secrets.CONSUMER_SECRET_MEVU }}

                  envkey_ACCESS_TOKEN_MEVU: ${{ secrets.ACCESS_TOKEN_MEVU }}

                  envkey_ACCESS_TOKEN_SECRET_MEVU: ${{ secrets.ACCESS_TOKEN_SECRET_MEVU }}

                  envkey_CONSUMER_KEY_UVA: ${{ secrets.CONSUMER_KEY_UVA }}

                  envkey_CONSUMER_SECRET_UVA: ${{ secrets.CONSUMER_SECRET_UVA }}

                  envkey_ACCESS_TOKEN_UVA: ${{ secrets.ACCESS_TOKEN_UVA }}

                  envkey_ACCESS_TOKEN_SECRET_UVA: ${{ secrets.ACCESS_TOKEN_SECRET_UVA }}
                  
                  envkey_CONSUMER_KEY_LUFI: ${{ secrets.CONSUMER_KEY_LUFI }}

                  envkey_CONSUMER_SECRET_LUFI: ${{ secrets.CONSUMER_SECRET_LUFI }}

                  envkey_ACCESS_TOKEN_LUFI: ${{ secrets.ACCESS_TOKEN_LUFI }}

                  envkey_ACCESS_TOKEN_SECRET_LUFI: ${{ secrets.ACCESS_TOKEN_SECRET_LUFI }}

                  envkey_CONSUMER_KEY_WOBA: ${{ secrets.CONSUMER_KEY_WOBA }}

                  envkey_CONSUMER_SECRET_WOBA: ${{ secrets.CONSUMER_SECRET_WOBA }}

                  envkey_ACCESS_TOKEN_WOBA: ${{ secrets.ACCESS_TOKEN_WOBA }}

                  envkey_ACCESS_TOKEN_SECRET_WOBA: ${{ secrets.ACCESS_TOKEN_SECRET_WOBA }}

                  envkey_CONSUMER_KEY_MAJ: ${{ secrets.CONSUMER_KEY_MAJ }}

                  envkey_CONSUMER_SECRET_MAJ: ${{ secrets.CONSUMER_SECRET_MAJ }}

                  envkey_ACCESS_TOKEN_MAJ: ${{ secrets.ACCESS_TOKEN_MAJ }}

                  envkey_ACCESS_TOKEN_SECRET_MAJ: ${{ secrets.ACCESS_TOKEN_SECRET_MAJ }}
                  
                  file_name: .env


            - name: Build the docker container

              run: docker build .


            - name: Run the script 🚀

              run: docker-compose -f docker-compose-facts.yml up
